spring.application.name = TravelBE
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/travel
spring.datasource.username=postgres
spring.datasource.password=2612002

spring.jpa.hibernate.ddl-auto=update
# 1. Cho phép hi?n th? câu l?nh SQL ra màn hình Console
spring.jpa.show-sql=true

# 2. ??nh d?ng câu l?nh SQL cho ??p, d? ??c (xu?ng dòng, th?t l?)
spring.jpa.properties.hibernate.format_sql=true

# 3. (Tùy ch?n) Hi?n th? giá tr? th?c t? c?a các tham s? truy?n vào d?u ?
logging.level.org.hibernate.orm.jdbc.bind=trace

cloudinary.cloud_name= Travel
cloudinary.api_key= 678323325373325
cloudinary.api_secret= WxlWYe5Ko9l4JlDw0yW8Cr3PIq0

# B?t endpoint api-docs và swagger-ui
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.packages-to-scan=com.travel.travelbe