spring.application.name = TravelBE
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/travel
spring.datasource.username=postgres
spring.datasource.password=2612002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud_name= Travel
cloudinary.api_key= 678323325373325
cloudinary.api_secret= WxlWYe5Ko9l4JlDw0yW8Cr3PIq0